name: AgroSolutions CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código-Fonte
        uses: actions/checkout@v4

      - name: Configurar o SDK do .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      # Restaura explicitamente as dependências de cada microsserviço
      - name: Restaurar Dependências Nuget
        run: |
          dotnet restore AlertServiceApi/AlertServiceApi.csproj
          dotnet restore IdentityServiceApi/IdentityServiceApi.csproj
          dotnet restore IngestionServiceApi/IngestionServiceApi.csproj
          dotnet restore PropertyServiceApi/PropertyServiceApi.csproj

      # Compila individualmente cada uma das APIs em modo Release
      - name: Compilar Solução (Build)
        run: |
          dotnet build AlertServiceApi/AlertServiceApi.csproj --no-restore --configuration Release
          dotnet build IdentityServiceApi/IdentityServiceApi.csproj --no-restore --configuration Release
          dotnet build IngestionServiceApi/IngestionServiceApi.csproj --no-restore --configuration Release
          dotnet build PropertyServiceApi/PropertyServiceApi.csproj --no-restore --configuration Release

      # Executa os testes de unidade se existirem (com salvaguarda caso não existam no MVP)
      - name: Executar Testes de Unidade
        run: |
          dotnet test --no-build --configuration Release --verbosity normal || echo "Nenhum projeto de testes configurado ou erro ignorado para o MVP."
