name: AgroSolutions CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código-Fonte
        uses: actions/checkout@v4

      - name: Configurar o SDK do .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      # Procura e restaura recursivamente todas as dependências das APIs (.csproj) na raiz do repositório
      - name: Restaurar Dependências Nuget
        run: dotnet restore

      # Compila todos os microsserviços C# encontrados na raiz de forma automática
      - name: Compilar Solução (Build)
        run: dotnet build --no-restore --configuration Release

      # Executa os testes de unidade se existirem, sem quebrar o pipeline se ainda não tiver projetos de testes criados
      - name: Executar Testes de Unidade
        run: |
          dotnet test --no-build --configuration Release --verbosity normal || echo "Nenhum projeto de testes configurado ou erro ignorado para o MVP."
